import type { MetadataRoute } from 'next';

import { site } from '@/content';

/**
 * lewix.ai/robots.txt
 *
 * For most of this site's life the origin served nothing here and everything
 * live was generated by Cloudflare's managed robots.txt: a `Content-Signal`
 * header and a block of AI-crawler `Disallow` rules that existed in no file in
 * this repo. **That is gone as of 2026-08-26.** Turning off the AI crawler
 * blocking in AI Crawl Control removed the managed block with it, and this
 * file is now the whole of robots.txt. It went from 1921 bytes to 85.
 *
 * The comment that used to stand here explained why the managed block was
 * "fine and left alone", and claimed the retrieval crawlers were all still
 * reachable. That was measurably untrue even then: Cloudflare was returning a
 * hard 403 to Claude-User, which is the agent that fetches a page because a
 * person asked about it. None of it describes anything that exists now, so it
 * has been removed rather than corrected.
 *
 * What remains is deliberate. Everything is crawlable, and both sitemaps are
 * declared: the marketing site's own, and Horizon's. Horizon is a separate
 * application mounted at /horizon, and robots.txt is scoped to the ORIGIN, so
 * `lewix.ai/horizon/robots.txt` is a file no crawler will ever read. This is
 * the only place the blog's sitemap can be announced.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: '/',
    },
    sitemap: [`${site.url}/sitemap.xml`, `${site.url}/horizon/sitemap.xml`],
    host: site.url,
  };
}
